apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-10-12T16:31:24Z"
  generation: 2
  labels:
    pod-template-hash: 77c49b47c
    workload.user.cattle.io/workloadselector: apps.deployment-parking-ai-facility-count-agent
  name: facility-count-agent-77c49b47c
  namespace: parking-ai
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: facility-count-agent
    uid: ff3f8810-9e15-4431-859d-2f1ff966f78d
  resourceVersion: "286915060"
  selfLink: /apis/apps/v1/namespaces/parking-ai/replicasets/facility-count-agent-77c49b47c
  uid: 4f112b90-b0c9-4baf-9d3f-c0c1cd349e24
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-template-hash: 77c49b47c
      workload.user.cattle.io/workloadselector: apps.deployment-parking-ai-facility-count-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod-template-hash: 77c49b47c
        workload.user.cattle.io/workloadselector: apps.deployment-parking-ai-facility-count-agent
    spec:
      affinity: {}
      containers:
      - image: mesaaz.azurecr.io/rainman:helium
        imagePullPolicy: IfNotPresent
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mesaaz-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 1
  observedGeneration: 2
  replicas: 1
