apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-10-18T15:36:44Z"
  generation: 2
  name: facililty-count-agent
  namespace: parking-ai
  resourceVersion: "288790752"
  selfLink: /apis/apps/v1/namespaces/parking-ai/deployments/facililty-count-agent
  uid: 0374abf1-6c20-4dbf-9a0c-0ac6dd8dd57b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-parking-ai-facililty-count-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-parking-ai-facililty-count-agent
    spec:
      affinity: {}
      containers:
      - command:
        - python3
        - countcars.py
        image: mesaaz.azurecr.io/rainman:helium
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/image_storage
          name: cam3d
        workingDir: /app
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mesaaz-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cam3d
        persistentVolumeClaim:
          claimName: cam3d01vw
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-18T15:37:17Z"
    lastUpdateTime: "2021-10-18T15:37:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-18T15:36:44Z"
    lastUpdateTime: "2021-10-18T15:37:17Z"
    message: ReplicaSet "facililty-count-agent-75d76d4d87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
