apiVersion: batch/v1
kind: CronJob
metadata:
  name: countagain
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: countagain
            image: mesa-az.azurecr/countcars
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - python3 /app/countcars.py
          restartPolicy: OnFailure
